####################################################################################################################
#
# Script: figure_5.R
# Project: An integrated multi-omic single cell atlas of human B cell identity
# Author: David Glass
# Date: 6-6-20
#
# Purpose: Generate subfigures of figure 5
#
# Instructions:
# This script requires processed_metabolism.csv, processed_biosynthesis.csv,
#  and processed_signaling.csv generated by other_preprocess.R
# Install all required packages (see LIBRARIES and/or Versions below)
# Set path (under USER INPUTS) to a unique directory
# Ensure the csv files are in that directory
# Run script
# One can also run the inputs and functions and then scroll down to MAIN
#  to choose which subfigures to generate.
# Note signaling output is slightly different from figures. The original clustering
# included additional data which was not used in the manuscript. Removing this data
# slightly altered clustering output - these minor differences do not affect any
# conclusions.
#
# Versions:
# R 3.6.3
# RStudio 1.2.5042
# ggplot2_3.3.0
# gplots_3.0.3
# relaimpo_2.2-3
# emdist_0.3-1
# viridis_0.5.1
# MASS_7.3-51.6 
# dplyr_1.0.0
# data.table_1.12.8
#
#######################################################################################################################



##### USER INPUTS #####

### Path to folder containing csv
path <- "~/example2/"



###### LIBRARIES ######

require(ggplot2)
require(gplots)
require(relaimpo)
require(emdist)
require(viridis)
require(MASS)
require(dplyr)
require(data.table)



##### INPUTS #####

images.path <- paste0(path, "images/")
clusters <- c("Transitional", "73- Naïve", "73+ Naïve", "27- Memory", "RB+ 27+ 73- Memory",
              "RB+ 27+ 73+ Memory", "RB- Memory", "95+ Memory", "19++ 11c+ Memory", "Plasma")
cluster.colors <- c("#362130", "#6D5D8C", "#01647F", "#4CA8C9", "#CC80B4",
                    "#826666", "#F0616E", "#4C0099", "#990000", "#FFADAF") %>%
  setNames(clusters)
isotypes <- c("IgD", "IgMD", "IgM", "IgG", "IgA", "ND")

metabolism.markers <- c("LDHA", "PFK2", "MCT1", "AMPK_p", "IDH1", "CytC", "ATPA5", "PPARa")
signaling <- c("p_PLCg2__pY759_", "p_ZAP70_Syk__Y319_Y352_", "p_p38__T180_Y182_")
factors <- c("subject", "cluster", "meta", "isotype", "BRU")



##### FUNCTIONS #####

metabolismBoxplots <- function(dt=met.dat, markers=metabolism.markers,
                               cc=cluster.colors, ip=images.path) {
  # Generates boxplots of metabolism markers
  # Inputs:
  #   dt - metabolism data.table
  #   markers - metabolism marker names
  #   cc - named vector of cluster hex colors
  #   ip - directory for images
  # Outputs:
  #   eps file of boxplots
  melted <- melt(dt[, c(markers, "meta"), with=F],
                 id.vars="meta",
                 variable.name="marker",
                 value.name="expression") %>%
    .[, marker:=factor(marker, markers)]
  ggplot(melted, aes(meta, expression, fill=meta)) + facet_wrap(.~marker, nrow=2) +
    geom_boxplot(outlier.shape=NA) + theme_bw() +
    scale_fill_manual(values=cc) +
    theme(axis.text.x=element_blank(), legend.position="none",
          panel.grid.major.x=element_blank(), axis.ticks.x=element_blank()) +
    scale_y_continuous(limits=c(0,1.3))
  ggsave(paste0(ip, "figure_5b.eps"), width=8, height=5)
}


metabolismStats <- function(dt=met.dat, markers=metabolism.markers) {
  # Generates boxplots of metabolism markers
  # Inputs:
  #   dt - metabolism data.table
  #   markers - metabolism marker names
  # Outputs:
  #   comparisons - data.table reporting results of ks test for each marker
  
  # 2 pw comparisons per marker - plasma vs highest mem; highest mem vs 2nd highest mem
  comparisons <- data.table(matrix(ncol=4, nrow=0)) %>%
    setnames(c("marker", "meta1", "meta2", "pvalue"))
  values <- dt[, lapply(.SD, median), .SDcols=markers, by=meta]
  high.memory <- c("RB+ 27+ 73- Memory", "19++ 11c+ Memory") 
  for (mar in markers) {
    rank <- values[order(eval(parse(text=mar)), decreasing=T), meta]
    meta.1 <- rank[1] %>% as.character()
    meta.2 <- rank[rank %in% high.memory][1] %>% as.character()
    meta.3 <- rank[rank %in% high.memory][2] %>% as.character()
    
    n.sample.a <- table(dt[meta %in% c(meta.1, meta.2), meta]) %>%
      .[.>0] %>%
      min()
    n.sample.b <- table(dt[meta %in% c(meta.2, meta.3), meta]) %>%
      .[.>0] %>%
      min()
    
    set.seed(666)
    subsampled.a <- dt[meta %in% c(meta.1, meta.2), .SD[sample(.N, n.sample.a)], by=meta]
    subsampled.b <- dt[meta %in% c(meta.2, meta.3), .SD[sample(.N, n.sample.b)], by=meta]
    
    values.1 <- subsampled.a[meta==meta.1, mar, with=F] %>% as.matrix() %>% as.numeric()
    values.2 <- subsampled.a[meta==meta.2, mar, with=F] %>% as.matrix() %>% as.numeric()
    values.3 <- subsampled.b[meta==meta.2, mar, with=F] %>% as.matrix() %>% as.numeric()
    values.4 <- subsampled.b[meta==meta.3, mar, with=F] %>% as.matrix() %>% as.numeric()
    
    comparisons <- rbind(comparisons, data.table(marker=mar,
                                                 meta1=meta.1,
                                                 meta2=meta.2,
                                                 pvalue=ks.test(values.1, values.2, alternative="less")$p.value))
    comparisons <- rbind(comparisons, data.table(marker=mar,
                                                 meta1=meta.2,
                                                 meta2=meta.3,
                                                 pvalue=ks.test(values.3, values.4, alternative="less")$p.value))
  }
  bonferroni.multiplier <- nrow(comparisons)
  comparisons <- comparisons[, pvalue:=pvalue*bonferroni.multiplier]
  return(comparisons)
}


relativeImportanceMetabolism <- function(dt=met.dat, ip=images.path) {
  # Generates bar plots of contribution of variance explained
  # Inputs:
  #   dt - data.table
  #   ip - path to images folder
  # Outputs:
  #   eps image
  ldha.imp <- calc.relimp(formula=LDHA~meta+isotype, data=dt, rela=T, type="lmg", rank=F)
  pfk2.imp <- calc.relimp(formula=PFK2~meta+isotype, data=dt, rela=T, type="lmg", rank=F)
  mct1.imp <- calc.relimp(formula=MCT1~meta+isotype, data=dt, rela=T, type="lmg", rank=F)
  ampk.imp <- calc.relimp(formula=AMPK_p~meta+isotype, data=dt, rela=T, type="lmg", rank=F)
  idh1.imp <- calc.relimp(formula=IDH1~meta+isotype, data=dt, rela=T, type="lmg", rank=F)
  cytc.imp <- calc.relimp(formula=CytC~meta+isotype, data=dt, rela=T, type="lmg", rank=F)
  atpa.imp <- calc.relimp(formula=ATPA5~meta+isotype, data=dt, rela=T, type="lmg", rank=F)
  ppara.imp <- calc.relimp(formula=PPARa~meta+isotype, data=dt, rela=T, type="lmg", rank=F)

  gly.lmg <- (ldha.imp@lmg + pfk2.imp@lmg + mct1.imp@lmg)/3
  ox.phos.lmg <- (idh1.imp@lmg + cytc.imp@lmg + atpa.imp@lmg)/3

  temp <- data.table(gly=gly.lmg,
                     ox=ox.phos.lmg,
                     atp=ampk.imp@lmg,
                     fao=ppara.imp@lmg,
                     classification=c("phenotype", "isotype")) %>%
    melt(id.vars="classification", variable.name="marker", value.name="percent") %>%
    .[, percent:=percent*100] %>%
    .[, marker:=factor(marker, levels=c("gly", "atp", "ox", "fao"))]

  ggplot(temp, aes(marker, percent, fill=classification)) + geom_bar(stat="identity") +
    theme_bw() + theme(legend.position="none", panel.grid=element_blank()) +
    scale_fill_manual(values=c("#a01ea0", "#25a3a3"))
  ggsave(paste0(ip, "figure_5j_metabolism.eps"), width=2.2, height=4)
}


getDensity <- function(x, y, ...) {
  # Returns the 2D density vector for two numeric vectors
  # Inputs:
  #   x, y - numeric vectors
  #   ... additional arguments passed onto kde2d
  # Outputs:
  #   vector of density values
  dens <- MASS::kde2d(x, y, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii])
}


biosynthesisBiaxial <- function(dt=bio.dat, ip=images.path) {
  # Generates a biaxial of the biosynthesis measurements
  # Inputs:
  #   dt - biosynthesis data.table
  #   ip - directory for images
  # Outputs:
  #   png file of biaxial
  lm.out <- lm(puromycin~BrdU, dt)
  print(summary(lm.out))
  temp <- copy(dt[, .(BrdU, puromycin)])
  temp$density <- getDensity(temp$BrdU, temp$puromycin, n=100)
  ggplot(temp, aes(BrdU, puromycin, color=density)) + geom_point(size=0.5) +
    geom_smooth(method='lm', color="black", se=F, linetype="dashed") + theme_bw() +
    theme(legend.position="none", axis.text=element_blank(), axis.ticks=element_blank()) +
    labs(x=NULL, y=NULL) + scale_color_viridis()
  ggsave(paste0(ip, "figure_5c.png"), width=4, height=4)
}


biosynthesisViolins <- function(dt=bio.dat, cc=cluster.colors, ip=images.path) {
  # Makes violin plots of BRU and puromycin by meta
  # Inputs:
  #   dt - biosynthesis data.table
  #   cc - named vector of hex color codes for each cluster
  #   ip - directory for images
  # Outputs:
  #   eps plot
  melted <- melt(dt[, .(BrdU, puromycin, meta)],
                 id.vars="meta",
                 variable.name="marker",
                 value.name="expression") %>%
    .[, marker:=factor(marker, levels=c("BrdU", "puromycin"))]
  ggplot(melted, aes(marker, expression, fill=meta)) + geom_violin(width=0.9) + theme_bw() +
    stat_summary(fun=median, geom="point", shape=18, size=2, position=position_dodge(width=0.9)) +
    theme(panel.grid.major.x=element_blank()) + labs(x=NULL, y=NULL) + scale_fill_manual(values=cc)
  ggsave(paste0(ip, "figure_5d.eps"), width=10, height=3)
}


bruComparisons <- function(dt=bio.dat[meta=="Plasma"], fa=factors) {
  # Compares each marker between BRU+ and BRU- plasma cells
  # Inputs:
  #   dt - data.table
  #   fa - vector of factor column names
  # Outputs:
  #   comparisons - data.table of results
  comparisons <- data.table(matrix(ncol=3, nrow=0)) %>%
    setnames(c("marker", "pvalue", "difference"))
  markers <- setdiff(colnames(dt), c(factors, "BrdU"))
  for (col in markers) {
    values.1 <- dt[BRU==T, col, with=F] %>% as.matrix() %>% as.numeric()
    values.2 <- dt[BRU==F, col, with=F] %>% as.matrix() %>% as.numeric()
    results <- ks.test(values.1, values.2)
    dif <- median(values.1) - median(values.2)
    comparisons <- rbind(comparisons, data.table(marker=col, pvalue=results$p.value, difference=dif))
  }
  bonferroni.multiplier <- nrow(comparisons)
  comparisons <- comparisons[, pvalue:=pvalue*bonferroni.multiplier] %>%
    .[order(-abs(difference))]
  return(comparisons)
}


bruViolins <- function(dt=bio.dat[meta=="Plasma"], ip=images.path, com=bio.comparisons) {
  # Make violin plots of all significant markers between BRU high and low plasma cells
  # Inputs:
  #   dt - data.table
  #   ip - directory for images
  #   com - data.table of results
  # Outputs:
  #   eps plot
  com.slim <- com[pvalue<0.005]
  palette <- c("#ffadc8", "#ffc8ad")
  markers <- com.slim$marker
  melted <- melt(dt[, c(markers, "BRU"), with=F], id.vars="BRU", variable.name="marker", value.name="expression")

  ggplot(melted, aes(marker, expression, fill=BRU)) + theme_bw() + scale_fill_manual(values=palette) +
    geom_violin(width=0.9) + theme_bw() +
    stat_summary(fun=median, geom="point", shape=18, size=2, position=position_dodge(width=0.9)) +
    theme(panel.grid.major.x=element_blank(), legend.position="none")
  ggsave(paste0(ip, "figure_5e.eps"), height=3, width=2.5)
}


relativeImportanceBiosynthesis <- function(dt=bio.dat, ip=images.path) {
  # Generates bar plots of contribution of variance explained
  # Inputs:
  #   dt - data.table
  #   ip - path to images folder
  # Outputs:
  #   eps image
  puro.imp <- calc.relimp(formula=puromycin~meta+isotype, data=dt, rela=T, type="lmg", rank=F)
  bru.imp <- calc.relimp(formula=BrdU~meta+isotype, data=dt, rela=T, type="lmg", rank=F)

  temp <- data.table(bru=bru.imp@lmg, puro=puro.imp@lmg, classification=c("phenotype", "isotype")) %>%
    melt(id.vars="classification", variable.name="marker", value.name="percent") %>%
    .[, percent:=percent*100] %>%
    .[, marker:=factor(marker, levels=c("bru", "puro"))]

  ggplot(temp, aes(marker, percent, fill=classification)) + geom_bar(stat="identity") +
    theme_bw() + theme(legend.position="none", panel.grid=element_blank()) +
    scale_fill_manual(values=c("#a01ea0", "#25a3a3"))
  ggsave(paste0(ip, "figure_5j_biosynthesis.eps"), width=1.5, height=4)
}


signalingHeatmaps <- function(dt=sig.dat, sig=c(signaling, "light"), ip=images.path) {
  # Creates heatmaps for signaling dataset
  # Inputs:
  #   dt - signaling data.table
  #   sig - vector of signaling channel names
  #   ip - path to images folder
  # Outputs:
  #   eps images
  dose.meds <- dt[, lapply(.SD, median), .SDcols=sig, by=.(meta, dose)]
  iso.dose.meds <- dt[isotype!="ND", lapply(.SD, median), .SDcols=sig, by=.(isotype, dose)]

  for (marker in sig) {
    rg <- range(rbind(dose.meds[, marker, with=F], iso.dose.meds[, marker, with=F]))
    ggplot(dose.meds, aes(dose, meta, fill=eval(parse(text=marker)))) + geom_tile() +
      scale_fill_viridis(option="B", limits=rg) +
      theme_bw() + theme(legend.position="none") + theme(panel.grid=element_blank(), axis.title=element_blank()) +
      scale_y_discrete(limits=rev(levels(dt$meta)))
    ggsave(paste0(ip, "figure_5g_population", marker, ".eps"), width=2.5, height=4)

    ggplot(iso.dose.meds, aes(dose, isotype, fill=eval(parse(text=marker)))) + geom_tile() +
      scale_fill_viridis(option="B", limits=rg) +
      theme_bw() + theme(legend.position="none") + theme(panel.grid=element_blank(), axis.title=element_blank()) +
      scale_y_discrete(limits=rev(levels(dt$isotype)[1:5]))
    ggsave(paste0(ip, "figure_5g_isotype", marker, ".eps"), width=2.5, height=3.5)
  }
}


signalingContour <- function(dt=sig.dat, ip=images.path) {
  # Creates contour plots for signaling dataset
  # Inputs:
  #   dt - signaling data.table
  #   ip - path to images folder
  # Outputs:
  #   eps image
  ggplot(dt[dose %in% c(0, 1)], aes(p_ZAP70_Syk__Y319_Y352_, p_PLCg2__pY759_)) +
    geom_density_2d(aes(color=dose)) +
    facet_wrap(~meta, nrow=2) + theme_bw() + scale_color_manual(values=c("darkblue", "red")) +
    theme(legend.position="none") + scale_y_continuous(limits=c(0, 1.3)) + scale_x_continuous(limits=c(0, 1.3))
  ggsave(paste0(ip, "figure_5h.eps"), width=8.5, height=4)
}


calculateEMD <- function(dt=sig.dat, ip=images.path, sig=signaling) {
  # calculate earth mover's distance between 0 and 1 by population
  # Inputs:
  #   dt - signaling data.table
  #   ip - path to images folder
  #   sig - vector of signaling channel names
  # Outputs:
  #   eps images
  bcr.dist <- list()
  p38.dist <- list()
  temp <- dt[dose!=0.5, c("dose", "meta", sig), with=F] %>%
    .[, dose:=droplevels(dose)]
  for (pop in levels(temp$meta)) {
    d0 <- kde2d(as.matrix(temp[meta==pop & dose==0, p_ZAP70_Syk__Y319_Y352_]),
                as.matrix(temp[meta==pop & dose==0, p_PLCg2__pY759_]),
                n=30, lims=c(0, 1.3, 0, 1.3))
    d1 <- kde2d(as.matrix(temp[meta==pop & dose==1, p_ZAP70_Syk__Y319_Y352_]),
                as.matrix(temp[meta==pop & dose==1, p_PLCg2__pY759_]),
                n=30, lims=c(0, 1.3, 0, 1.3))
    a <- cbind(as.vector(d0$z)/sum(d0$z), as.matrix(expand.grid(d0$y, d0$x)))
    b <- cbind(as.vector(d1$z)/sum(d1$z), as.matrix(expand.grid(d1$y, d1$x)))
    bcr.dist[[pop]] <- emd(a, b)

    a <- as.matrix(temp[meta==pop & dose==0, p_p38__T180_Y182_]) %>%
      density(n=30, from=0, to=1.3) %>%
      cbind(.$y, .$x) %>%
      .[,2:3]
    b <- as.matrix(temp[meta==pop & dose==1, p_p38__T180_Y182_]) %>%
      density(n=30, from=0, to=1.3) %>%
      cbind(.$y, .$x) %>%
      .[,2:3]
    p38.dist[[pop]] <- emd(a, b)
  }

  ggplot(melt(as.data.table(bcr.dist)), aes(variable, value, fill=variable)) + geom_col() +
    scale_fill_manual(values=cluster.colors) + theme_bw() + coord_flip() +
    scale_x_discrete(limits=rev(levels(dt$meta))) +
    theme(legend.position="none", panel.grid.major.y=element_blank())
  ggsave(paste0(ip, "figure_5i_left.eps"), width=5, height=2.5)

  ggplot(melt(as.data.table(p38.dist)), aes(variable, value, fill=variable)) + geom_col() +
    scale_fill_manual(values=cluster.colors) + theme_bw() + coord_flip() +
    scale_x_discrete(limits=rev(levels(dt$meta))) +
    theme(legend.position="none", panel.grid.major.y=element_blank())
  ggsave(paste0(ip, "figure_5i_right.eps"), width=5, height=2.5)
}


relativeImportanceSignaling <- function(dt=sig.dat, ip=images.path) {
  # Generates bar plots of contribution of variance explained
  # Inputs:
  #   dt - data.table
  #   ip - path to images folder
  # Outputs:
  #   eps image
  plc.imp <- calc.relimp(formula=p_PLCg2__pY759_~meta+isotype, data=dt[dose==1], rela=T, type="lmg", rank=F)
  zap.imp <- calc.relimp(formula=p_ZAP70_Syk__Y319_Y352_~meta+isotype, data=dt[dose==1], rela=T, type="lmg", rank=F)
  p38.imp <- calc.relimp(formula=p_p38__T180_Y182_~meta+isotype, data=dt[dose==1], rela=T, type="lmg", rank=F)

  temp <- data.table(p38=p38.imp@lmg, zap=zap.imp@lmg, plc=plc.imp@lmg, classification=c("phenotype", "isotype")) %>%
    melt(id.vars="classification", variable.name="marker", value.name="percent") %>%
    .[, percent:=percent*100] %>%
    .[, marker:=factor(marker, levels=c("zap", "plc", "p38"))]

  ggplot(temp, aes(marker, percent, fill=classification)) + geom_bar(stat="identity") +
    theme_bw() + theme(legend.position="none", panel.grid=element_blank()) +
    scale_fill_manual(values=c("#a01ea0", "#25a3a3"))
  ggsave(paste0(ip, "figure_5j_signaling.eps"), width=1.5, height=4)
}



##### MAIN #####

if (!dir.exists(images.path)) dir.create(images.path)

# Metabolism dataset
met.dat <- fread(paste0(path, "processed_metabolism.csv"), stringsAsFactors=T) %>%
  .[, isotype:=factor(isotype, isotypes)] %>%
  .[, meta:=factor(meta, clusters)] %>%
  .[, cluster:=factor(cluster)] %>%
  .[, subject:=factor(subject)]

# Figure 5b
metabolismBoxplots()
met.stats <- metabolismStats()

# Figure 5j metabolism
relativeImportanceMetabolism()

rm(met.dat)

# Biosynthesis dataset
bio.dat <- fread(paste0(path, "processed_biosynthesis.csv"), stringsAsFactors=T) %>%
  .[, isotype:=factor(isotype, isotypes)] %>%
  .[, meta:=factor(meta, clusters)] %>%
  .[, cluster:=factor(cluster)] %>%
  .[, subject:=factor(subject)]

# Figure 5c
biosynthesisBiaxial()

# Figure 5d
biosynthesisViolins()

# Figure 5e
bio.dat[BrdU>0.75, BRU:=T]
bio.dat[BrdU<0.75, BRU:=F]
bio.comparisons <- bruComparisons()
bruViolins()

# Figure 5j biosynthesis
relativeImportanceBiosynthesis()

rm(bio.dat)

# Signaling dataset
sig.dat <- fread(paste0(path, "processed_signaling.csv"), stringsAsFactors=T) %>%
  .[, isotype:=factor(isotype, isotypes)] %>%
  .[, meta:=factor(meta, clusters)] %>%
  .[, subject:=factor(subject)] %>%
  .[, dose:=factor(dose)]

# Figure 5g
signalingHeatmaps()

# Figure 5h
signalingContour()

# Figure 5i
calculateEMD()

# Figure 5j signaling
relativeImportanceSignaling()
