####################################################################################################################
#
# Script: figure_6.R
# Project: An integrated multi-omic single cell atlas of human B cell identity
# Author: David Glass
# Date: 6-8-20
#
# Purpose: Generate subfigures of figure 6
#
# Instructions:
# This script requires processed_tissue.csv generated by other_preprocess.R
# Install all required packages (see LIBRARIES and/or Versions below)
# Set path (under USER INPUTS) to a unique directory
# Ensure the csv file is in that directory
# Run script
# One can also run the inputs and functions and then scroll down to MAIN
#  to choose which subfigures to generate.
#
# Versions:
# R 3.6.3
# RStudio 1.2.5042
# uwot_0.1.8
# ggplot2_3.3.0
# pheatmap_1.0.12
# viridis_0.5.1
# nationalparkcolors_0.1.0
# dplyr_1.0.0
# data.table_1.12.8
#
#######################################################################################################################



##### USER INPUTS #####

### Path to folder containing csv
path <- "~/example2/"



###### LIBRARIES ######

require(uwot)
require(ggplot2)
require(pheatmap)
require(viridis)
require(nationalparkcolors)
require(dplyr)
require(data.table)



##### INPUTS #####

images.path <- paste0(path, "images/")
clusters <- c("Transitional", "73- Naïve", "73+ Naïve", "27- Memory", "RB+ 27+ 73- Memory",
              "RB+ 27+ 73+ Memory", "RB- Memory", "95+ Memory", "19++ 11c+ Memory", "Plasma",
              "Germinal Center", "39+ Tonsilar")
cluster.colors <- c("#362130", "#6D5D8C", "#01647F", "#4CA8C9", "#CC80B4", "#826666",
                    "#F0616E", "#4C0099", "#990000", "#FFADAF", "#55D6BE", "#861657") %>%
  setNames(clusters)
isotypes <- c("IgD", "IgMD", "IgM", "IgG", "IgA", "ND")
isotype.colors <- magma(6) %>%
  rev() %>%
  setNames(isotypes)
isotype.colors["ND"] <- "#D1D2D4"
isotype.channels <- isotypes[c(1,3,4,5)]
tissues <- c("PB", "BM", "T", "LN")
tissue.colors <- park_palette("Everglades", 5)[5:2] %>%
  setNames(tissues)
factors <- c("tissue", "donor", "run", "isotype", "cluster", "meta")


##### FUNCTIONS #####

compareTissueDistributions <- function(dt=dat, channels=setdiff(colnames(dat), factors)) {
  # Uses the KS test to find which markers are differentially expressed between tissues
  # Inputs:
  #   dt - data.table
  #   channels - vector of numeric column names
  # Outputs:
  #   comparisons - data.table of tissue1, tissue2, marker, p value, and expression difference
  comparisons <- data.table(matrix(ncol=5, nrow=0)) %>%
    setnames(c("tissue1", "tissue2", "marker", "pvalue", "difference"))
  combinations <- combn(factor(levels(dt$tissue), levels(dt$tissue)), 2)
  n.sample <- min(table(dt[, .(tissue)])) # smallest gate for every panel
  set.seed(666)
  subsampled <- dt[, .SD[sample(.N, n.sample)], by=.(tissue)]
  for (marker in channels) {
    for (i in seq(ncol(combinations))) {
      values.1 <- subsampled[tissue==combinations[1,i], marker, with=F] %>% as.matrix() %>% as.numeric()
      values.2 <- subsampled[tissue==combinations[2,i], marker, with=F] %>% as.matrix() %>% as.numeric()
      results <- ks.test(values.1, values.2)
      dif <- dt[tissue==combinations[1,i], lapply(.SD, median, na.rm=T), .SDcols=marker] -
        dt[tissue==combinations[2,i], lapply(.SD, median, na.rm=T), .SDcols=marker]
      comparisons <- rbind(comparisons, data.table(marker=marker,
                                                   tissue1=combinations[1,i],
                                                   tissue2=combinations[2,i],
                                                   pvalue=results$p.value,
                                                   difference=dif[[1]]))
    }
  }
  bonferroni.multiplier <- ncol(comparisons)
  comparisons <- comparisons[, pvalue:=pvalue*bonferroni.multiplier] %>%
    .[order(-abs(difference))]
  return(comparisons)
}


tissueViolins <- function(dt=dat, tc=tissue.colors, pa=images.path, channels) {
  # Makes violin plots for all tissues for all markers
  # Inputs:
  #   dt - data.table
  #   tc - named vector of tissue colors
  #   ip - path to images folder
  #   channels - vector of column names
  # Outputs:
  #   eps of violin plots
  melted <- melt(dt[, c(channels, "tissue"), with=F], id.vars="tissue", variable.name="channel", value.name="expression")
  
  ggplot(melted, aes(tissue, expression, fill=tissue)) + geom_violin(scale="width") + facet_wrap(~channel, nrow=3) +
    stat_summary(fun=median, geom="point", shape=18, size=2, position=position_dodge(width=1)) + theme_bw() +
    scale_fill_manual(values=tc) + theme(text=element_text(size=20), axis.text.x=element_blank(),
                                         axis.title.x=element_blank(), axis.ticks=element_blank())
  ggsave(paste0(pa, "figure_6b.eps"), height=6, width=10)
}


isotypeTissue <- function(dt=dat, ic=isotype.colors, pa=images.path, tc=tissue.colors) {
  # Generates barplots of isotype usage by tissue
  # Inputs:
  #   dt - data.table
  #   ic - named vector of isotype colors
  #   pa - path to images folder
  #   tc - named vector of tissue colors
  # Outputs:
  #   eps of isotypes stacked bar graph
  temp <- table(dt[, .(isotype, tissue)]) %>%
    as.data.table() %>%
    .[, P:=100*N/sum(N), by=tissue] %>%
    .[, isotype:=factor(isotype, levels=c("IgD", "IgMD", "IgM", "IgG", "IgA", "ND"))] %>%
    .[, tissue:=factor(tissue, names(tc))]
  
  ggplot(temp, aes(tissue, P, fill=isotype)) + geom_col(position="fill") +
    theme_bw() + scale_fill_manual(values=ic) +
    theme(text=element_text(size=20), panel.grid=element_blank(), legend.position="none")
  ggsave(paste0(pa, "figure_6c.eps"), width=2.6, height=4.5)
}


clusterTissueBar <- function(dt=dat, cc=cluster.colors, pa=images.path, tc=tissue.colors) {
  # Generates non-stacked barplots of meta proportion by tissue
  # Inputs:
  #   dt - data.table
  #   cc - named vector of cluster colors
  #   pa - path to images folder
  #   tc - named vector of tissue colors
  # Outputs:
  #   eps of bar graph
  temp <- table(dt[, .(meta, tissue)]) %>%
    as.data.table() %>%
    .[, P:=100*N/sum(N), by=tissue] %>%
    .[, meta:=factor(meta, levels=names(cc))] %>%
    .[, tissue:=factor(tissue, names(tc))]
  
  ggplot(temp, aes(meta, P, fill=tissue)) + geom_col(position=position_dodge()) +
    theme_bw() + scale_fill_manual(values=tc) + labs(x=NULL, y="Percent of total B cells") +
    theme(text=element_text(size=20), legend.position="none",
          axis.text.x=element_text(hjust=1, angle=90))
  ggsave(paste0(pa, "figure_6d.eps"), width=6, height=5)
}


distanceTissueHeatmap <- function(dt=dat, tc=tissue.colors, pa=images.path) {
  # Generates heatmap of distance per tissue by meta proporttions
  # Inputs:
  #   dt - data.table
  #   tc - named vector of tissue colors
  #   pa - path to images folder
  # Outputs:
  #   eps of cluster bar graph
  temp <- table(dt[, .(meta, tissue)]) %>%
    as.data.table() %>%
    .[, P:=100*N/sum(N), by=tissue] %>%
    .[, tissue:=factor(tissue, names(tc))] %>%
    .[, N:=NULL] %>%
    dcast(tissue~meta, value.var="P")
  
  distances <- dist(as.matrix(temp, rownames="tissue"), method="manhattan", diag=T, upper=T)
  
  ar <- as.data.frame(temp[, .(tissue)])
  rownames(ar) <- temp[, tissue]
  ac <- list(tissue=tc)
  
  setEPS()
  postscript(paste0(pa, "figure_6e.eps"), width=5.7, height=5)
  pheatmap(mat=distances, annotation_row=ar, annotation_col=ar, annotation_colors=ac,
           color=viridis(20))
  dev.off()
}


makeBiaxials <- function(dt=dat, cc=cluster.colors, pa=images.path) {
  # Generates two biaxials
  # Inputs:
  #   dt - data.table
  #   cc - named vector of cluster colors
  #   pa - path to images folder
  # Outputs:
  #   png of dot plots
  subsampled <- dt[tissue=="T"] # showing only tonsil
  subsampled[meta=="Germinal Center", GC:="Germinal Center"]
  subsampled[is.na(GC), GC:="B cells"]
  subsampled <- subsampled[order(GC)]
  
  ggplot(subsampled, aes(CD32, CD38, color=GC)) + geom_point() +
    theme_bw() + theme(legend.position="none", text=element_text(size=20)) +
    scale_color_manual(values=list(`Germinal Center`=cc["Germinal Center"], `B cells`="black"))
  ggsave(paste0(pa, "figure_6f.png"), width=5, height=5)
  
  subsampled[meta=="39+ Tonsilar", ton:="Tonsilar"]
  subsampled[is.na(ton), ton:="B cells"]
  subsampled <- subsampled[order(ton)]
  
  ggplot(subsampled, aes(CD39, CD185, color=ton)) + geom_point() +
    theme_bw() + theme(legend.position="none", text=element_text(size=20)) +
    scale_color_manual(values=list(`Tonsilar`=cc["39+ Tonsilar"], `B cells`="black"))
  ggsave(paste0(pa, "figure_6g.png"), width=5, height=5)
}


makeUmap <- function(dt=dat, tc=tissue.colors, ic=isotype.colors,
                     cc=cluster.colors, pa=paste0(images.path, "figure_6_umap/"),
                     fa=factors, iso.channels=isotype.channels) {
  # Generates umap subsampled by tissue and meta
  # Inputs:
  #   dt - data.table
  #   tc - named vector of tissue colors
  #   ic - named vector of isotype colors
  #   cc - named vector of cluster colors
  #   pa - path to images folder
  #   fa - vector of factor column names
  #   iso.channels - vector of isotype column names
  # Outputs:
  #   umap pngs
  if (!dir.exists(pa)) dir.create(pa)
  
  n.sample <- min(table(dt$tissue))
  set.seed(666)
  subsampled <- dt[, .SD[sample(.N, n.sample)], by=.(tissue)]
  n.sample.2 <- min(table(subsampled$meta))
  subsampled <- subsampled[, .SD[sample(.N, n.sample.2)], by=.(meta)]
  
  cols <- setdiff(colnames(dt), c(fa, iso.channels))
  set.seed(666)
  umap.out <- umap(subsampled[, cols, with=F], n_neighbors=100, min_dist=0.3)
  subsampled[, `:=`(umap.1=umap.out[,1], umap.2=umap.out[,2])]
  
  # meta
  ggplot(subsampled, aes(umap.1, umap.2)) + geom_density2d(color="#CCCCCC") +
    geom_point(size=0.8, aes(color=meta)) +
    theme_bw() + labs(x=NULL, y=NULL) +
    xlim(min(subsampled$umap.1)-1, max(subsampled$umap.1)+1) +
    ylim(min(subsampled$umap.2)-1.5, max(subsampled$umap.2)+1.5) +
    scale_color_manual(values=cc) + labs(x=NULL, y=NULL) +
    theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.border=element_blank(),
          axis.ticks=element_blank(), axis.text=element_blank(), legend.position="none")
  ggsave(paste0(pa, "umap_meta.png"))
  
  # donor
  ggplot(subsampled, aes(umap.1, umap.2)) + geom_density2d(color="#CCCCCC") +
    geom_point(size=0.8, aes(color=donor)) +
    theme_bw() + labs(x=NULL, y=NULL) +
    xlim(min(subsampled$umap.1)-1, max(subsampled$umap.1)+1) +
    ylim(min(subsampled$umap.2)-1.5, max(subsampled$umap.2)+1.5) +
    labs(x=NULL, y=NULL) +
    theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.border=element_blank(),
          axis.ticks=element_blank(), axis.text=element_blank(), legend.position="none")
  ggsave(paste0(pa, "umap_donor.png"))
  
  # isotype
  ggplot(subsampled, aes(umap.1, umap.2)) + geom_density2d(color="#CCCCCC") +
    geom_point(size=0.8, aes(color=isotype)) +
    theme_bw() + labs(x=NULL, y=NULL) +
    xlim(min(subsampled$umap.1)-1, max(subsampled$umap.1)+1) +
    ylim(min(subsampled$umap.2)-1.5, max(subsampled$umap.2)+1.5) +
    scale_color_manual(values=ic) + labs(x=NULL, y=NULL) +
    theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.border=element_blank(),
          axis.ticks=element_blank(), axis.text=element_blank(), legend.position="none")
  ggsave(paste0(pa, "umap_isotype.png"))
  
  # tissue
  ggplot(subsampled, aes(umap.1, umap.2)) + geom_density2d(color="#CCCCCC") +
    geom_point(size=0.8, aes(color=tissue)) +
    theme_bw() + labs(x=NULL, y=NULL) +
    xlim(min(subsampled$umap.1)-1, max(subsampled$umap.1)+1) +
    ylim(min(subsampled$umap.2)-1.5, max(subsampled$umap.2)+1.5) +
    scale_color_manual(values=tc) + labs(x=NULL, y=NULL) +
    theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.border=element_blank(),
          axis.ticks=element_blank(), axis.text=element_blank(), legend.position="none")
  ggsave(paste0(pa, "umap_tissue.png"))
  
  # marker
  for (marker in c(cols, iso.channels)) {
    subsampled[eval(parse(text=marker))>1, eval(quote(marker)):=1]
    ggplot(subsampled, aes(umap.1, umap.2)) + geom_density2d(color="#CCCCCC") +
      geom_point(size=0.8, aes(color=eval(parse(text=marker)))) +
      theme_bw() + labs(x=NULL, y=NULL) +
      xlim(min(subsampled$umap.1)-1, max(subsampled$umap.1)+1) +
      ylim(min(subsampled$umap.2)-1.5, max(subsampled$umap.2)+1.5) +
      scale_color_viridis(option="B", limits=c(0,1)) + labs(x=NULL, y=NULL) +
      theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.border=element_blank(),
            axis.ticks=element_blank(), axis.text=element_blank(), legend.position="none")
    ggsave(paste0(pa, "umap_", marker, ".png"))
  }
}



##### MAIN #####

if (!dir.exists(images.path)) dir.create(images.path)
dat <- fread(paste0(path, "processed_tissue.csv"), stringsAsFactors=T) %>%
  .[, `:=`(donor=factor(donor, 1:11),
           isotype=factor(isotype, isotypes),
           tissue=factor(tissue, tissues),
           meta=factor(meta, names(cluster.colors)),
           cluster=factor(cluster, sort(unique(cluster))))]


# Figure 6b
comparisons.tissue <- compareTissueDistributions()
sig.markers <- comparisons.tissue[pvalue<0.005 & abs(difference)>0.1] %>%
  .[, marker] %>%
  unique()
tissueViolins(channels=sig.markers)

# Figure 6c
isotypeTissue()

# Figure 6d
clusterTissueBar()

# Figure 6e
distanceTissueHeatmap()

# Figure 6f-g
makeBiaxials()

# Figure 6h
makeUmap()
