####################################################################################################################
#
# Script: figure_4.R
# Project: An integrated multi-omic single cell atlas of human B cell identity
# Author: David Glass
# Date: 6-2-20
#
# Purpose: Generate subfigures of figure 4
#
# Instructions:
# This script requires processed_surface.csv generated by other_preprocess.R
# Install all required packages (see LIBRARIES and/or Versions below)
# Set path (under USER INPUTS) to a unique directory
# Ensure the csv file is in that directory
# Run script
# One can also run the inputs and functions and then scroll down to MAIN
#  to choose which subfigures to generate.
#
# Versions:
# R 3.6.3
# RStudio 1.2.5042
# uwot_0.1.8
# ggplot2_3.3.0
# pheatmap_1.0.12
# gplots_3.0.3
# relaimpo_2.2-3
# viridis_0.5.1
# dplyr_1.0.0
# data.table_1.12.8
#
#######################################################################################################################



##### USER INPUTS #####

### Path to folder containing csv
path <- "~/example2/"



###### LIBRARIES ######

require(uwot)
require(ggplot2)
require(pheatmap)
require(gplots)
require(relaimpo)
require(viridis)
require(dplyr)
require(data.table)



##### INPUTS #####

images.path <- paste0(path, "images/")
factors <- c("gate", "subject", "cluster", "meta", "isotype")
gates <- c("Transitional","Naïve","Non-switched","Switched", "Ungated") %>%
  factor(., .)
gate.colors <- c(viridis(4), "#FFADAF", "#b6b6b6")
names(gate.colors) <- gates
clusters <- c("Transitional", "73- Naïve", "73+ Naïve", "27- Memory", "RB+ 27+ 73- Memory",
              "RB+ 27+ 73+ Memory", "RB- Memory", "95+ Memory", "19++ 11c+ Memory", "Plasma")
cluster.colors <- c("#362130", "#6D5D8C", "#01647F", "#4CA8C9", "#CC80B4",
                    "#826666", "#F0616E", "#4C0099", "#990000", "#FFADAF") %>%
  setNames(clusters)
isotypes <- c("IgD", "IgMD", "IgM", "IgG", "IgA", "ND")
isotype.colors <- magma(6) %>%
  rev() %>%
  setNames(isotypes)
isotype.colors["ND"] <- "#D1D2D4"



##### FUNCTIONS #####

metaHeatmap <- function(med=medians, ip=images.path) {
  # Makes a heatmap of the median expression of subsets
  # Inputs:
  #   med - data.table of marker medians
  #   ip - vector of path
  # Outputs:
  #   eps of of heatmap
  med.matrix <- as.matrix(med, rownames="meta")

  postscript(paste0(ip, "figure_4b.eps"), width=12, height=5.5)
  heatmap.2(x=med.matrix, col=inferno(n=20), tracecol=NA, lwid=c(1,12), lhei=c(1.25,6), key=FALSE, mar=c(10,8), cexRow=0.5,
            dendrogram="column", Rowv=F)
  dev.off()
}


makeUmap <- function(dt=dat, ip=paste0(images.path, "figure_4_umap/"), mar=markers,
                     gc=gate.colors, cc=cluster.colors,
                     ic=isotype.colors, n.sample=1000,
                     all.m=all.markers) {
  # Makes Umap
  # Inputs:
  #   dt - data.table
  #   ip - character vector to path
  #   mar - channels to use for manifold
  #   gc - vector of gate colors
  #   cc - vector of cluster colors
  #   ic - vector of isotype colors
  #   n.sample - number of cells to sample per metacluster
  #   all.m - vector of markers to visualize
  # Outputs:
  #   png images of files
  if (!dir.exists(ip)) dir.create(ip)
  
  RNGkind(sample.kind = "Rounding") # Backwards compatible seed selection
  set.seed(666)
  subsampled <- copy(dt[, .SD[sample(.N, n.sample)], by=meta])
  umap.out <- uwot::umap(subsampled[, mar, with=F], min_dist=0.6, n_neighbors=40)
  subsampled[, `:=`(umap.1=umap.out[,1], umap.2=umap.out[,2])]
  # subsampling is the same but umap varied slightly after R upgrade
  
  # meta
  ggplot(subsampled, aes(umap.1, umap.2)) + geom_density2d(color="#CCCCCC") +
    geom_point(size=0.8, aes(color=meta)) +
    theme_bw() + scale_color_manual(values=cc) + labs(x=NULL, y=NULL) +
    xlim(min(subsampled$umap.1)-.5, max(subsampled$umap.1)+.5) +
    ylim(min(subsampled$umap.2)-1, max(subsampled$umap.2)+1) +
    theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.border=element_blank(),
          axis.ticks=element_blank(), axis.text=element_blank(), legend.position="none")
  ggsave(paste0(ip, "umap_meta.png"), width=5, height=5)
  
  # isotype
  ggplot(subsampled, aes(umap.1, umap.2)) + geom_density2d(color="#CCCCCC") +
    geom_point(size=0.8, aes(color=isotype)) +
    theme_bw() + scale_color_manual(values=ic) + labs(x=NULL, y=NULL) +
    xlim(min(subsampled$umap.1)-.5, max(subsampled$umap.1)+.5) +
    ylim(min(subsampled$umap.2)-1, max(subsampled$umap.2)+1) +
    theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.border=element_blank(),
          axis.ticks=element_blank(), axis.text=element_blank(), legend.position="none")
  ggsave(paste0(ip, "umap_isotype.png"), width=5, height=5)
  
  # gate
  ggplot(subsampled, aes(umap.1, umap.2)) + geom_density2d(color="#CCCCCC") +
    geom_point(size=0.8, aes(color=gate)) +
    theme_bw() + scale_color_manual(values=gc) + labs(x=NULL, y=NULL) +
    xlim(min(subsampled$umap.1)-.5, max(subsampled$umap.1)+.5) +
    ylim(min(subsampled$umap.2)-1, max(subsampled$umap.2)+1) +
    theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.border=element_blank(),
          axis.ticks=element_blank(), axis.text=element_blank(), legend.position="none")
  ggsave(paste0(ip, "umap_gates.png"), width=5, height=5)
  
  # subject
  ggplot(subsampled, aes(umap.1, umap.2)) + geom_density2d(color="#CCCCCC") +
    geom_point(size=0.8, aes(color=subject)) +
    theme_bw() + labs(x=NULL, y=NULL) +
    xlim(min(subsampled$umap.1)-.5, max(subsampled$umap.1)+.5) +
    ylim(min(subsampled$umap.2)-1, max(subsampled$umap.2)+1) +
    theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.border=element_blank(),
          axis.ticks=element_blank(), axis.text=element_blank(), legend.position="none")
  ggsave(paste0(ip, "umap_subjects.png"), width=5, height=5)
  
  # markers
  for (marker in all.m) {
    subsampled[eval(parse(text=marker))>1, eval(quote(marker)):=1]
    ggplot(subsampled, aes(umap.1, umap.2)) + geom_density2d(color="#CCCCCC") +
      geom_point(size=0.8, aes(color=eval(parse(text=marker)))) +
      theme_bw() + labs(x=NULL, y=NULL) +
      xlim(min(subsampled$umap.1)-.5, max(subsampled$umap.1)+.5) +
      ylim(min(subsampled$umap.2)-1, max(subsampled$umap.2)+1) +
      scale_color_viridis(option="B", limits=c(0,1)) + labs(x=NULL, y=NULL) +
      theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.border=element_blank(),
            axis.ticks=element_blank(), axis.text=element_blank(), legend.position="none")
    ggsave(paste0(ip, "umap_", marker, ".png"), width=5, height=5)
  }
}


distanceHeatmap <- function(med=medians, cc=cluster.colors, ip=images.path, mar=markers) {
  # Generates heatmap of distance per donor/tissue by meta
  # Inputs:
  #   med - data.table of medians by meta
  #   cc - named vector of meta colors
  #   ip - path to images folder
  #   mar - character vector of columns to calculate distances from
  # Outputs:
  #   eps of cluster bar graph
  med.matrix <- as.matrix(med[, c(mar, "meta"), with=F], rownames="meta")
  euc.dist <- as.matrix(dist(med.matrix, method="euclidean", diag=T, upper=T))
  
  # looking for most similar pop
  x <- as.data.table(euc.dist, keep.rownames="Pop1") %>%
    melt(id.vars="Pop1", variable.name="Pop2", value.name="Distance") %>%
    .[order(Distance)] %>%
    .[Distance>0]
  x[!duplicated(x$Pop1)]
  
  ar <- data.frame(meta=names(cc))
  rownames(ar) <- names(cc)
  ac <- list(meta=cc)
  
  setEPS()
  postscript(paste0(ip, "figure_4e.eps"), width=5, height=5)
  pheatmap(mat=euc.dist, annotation_row=ar, annotation_col=ar, annotation_colors=ac, color=viridis(20),
           legend=F, annotation_legend=F)
  dev.off()
}


isotypeBar <- function(dt=dat, ic=isotype.colors, ip=images.path) {
  # Generates bar of isotype usage by metacluster
  # Inputs:
  #   dt - data.table
  #   ip - path to images folder
  #   ic - vector of isotype colors
  # Outputs:
  #   eps image
  ggplot(dt, aes(meta, fill=isotype)) + geom_bar(position="fill") +
    theme_bw() +
    theme(axis.text.x=element_text(hjust=1, angle=90), panel.grid=element_blank(), legend.position="none") +
    scale_fill_manual(values=ic) +
    labs(x=NULL, y="Proportion")
  ggsave(paste0(ip, "figure_4f.eps"), height=4.5, width=2.5)
}


populationBar <- function(dt=dat, ip=images.path) {
  # Generate bars of classification by isotype usage
  # Inputs:
  #   dt - data.table
  #   ip - path to images folder
  # Outputs:
  #   eps image
  dt[meta %in% c("Transitional",  "73- Naïve", "73+ Naïve"), type:="a-naive"]
  dt[!meta %in% c("Transitional",  "73- Naïve", "73+ Naïve"), type:="experienced"]
  
  dt[gate %in% c("Transitional", "Naïve"), gate.type:="a-naive"]
  dt[gate %in% c("Non-switched", "Switched", "Plasmablast"), gate.type:="experienced"]
  dt[gate=="Ungated", gate.type:="ungated"]

  new <- table(dt$isotype, dt$type) %>%
    apply(1, function(x) x/sum(x)*100) %>%
    as.data.table(keep.rownames="type") %>%
    melt()
  old <- table(dt$isotype, dt$gate.type) %>%
    apply(1, function(x) x/sum(x)*100) %>%
    as.data.table(keep.rownames="type") %>%
    melt()

  my.pal <- c("#7F7F7F", "#2E73AF", "#000000") %>%
    setNames(c("a-naive", "experienced", "ungated"))

  ggplot(new, aes(variable, value, fill=type)) + geom_col() +
    scale_fill_manual(values=my.pal) +
    theme_bw() +
    theme(axis.text.x=element_text(hjust=1, angle=90), panel.grid=element_blank(), legend.position="none") +
    labs(x=NULL, y="Percent")
  ggsave(paste0(ip, "figure_4g_right.eps"), height=4.5, width=2.5)

  ggplot(old, aes(variable, value, fill=type)) + geom_col() +
    scale_fill_manual(values=my.pal) +
    theme_bw() +
    theme(axis.text.x=element_text(hjust=1, angle=90), panel.grid=element_blank(), legend.position="none") +
    labs(x=NULL, y="Percent")
  ggsave(paste0(ip, "figure_4g_left.eps"), height=4.5, width=2.5)
}


isotypeContours <- function(dt=dat, ip=images.path) {
  # Generates contour plots by isotype
  # Inputs:
  #   dt - data.table
  #   ip - path to images folder
  # Outputs:
  #   eps image
  temp <- dt[isotype!="ND"] %>%
    .[, .(median(CD79b), median(light)), by=.(isotype, subject)] %>%
    setnames(c("V1", "V2"), c("CD79b", "light")) %>%
    .[, `:=`(CD79b.mean=mean(CD79b), CD79b.sem=sd(CD79b)/sqrt(3),
             light.mean=mean(light), light.sem=sd(light)/sqrt(3)), by=isotype] %>%
    .[, `:=`(subject=NULL, CD79b=NULL, light=NULL)] %>%
    unique()
  
  dat.lite <- dt[isotype!="ND"] %>%
    .[, CD79b.median:=median(CD79b), by=isotype] %>%
    .[, light.median:=median(light), by=isotype]

  print("CD79b Surface Ig correlations by isotype")
  print(dt[, cor(CD79b, light), by=isotype])

  ggplot(dat.lite, aes(CD79b, light)) + geom_density2d(aes(color=..level..), size=0.5) +
    facet_wrap(~isotype, nrow=1) + theme_bw() + scale_color_viridis_c(option="D") +
    theme(legend.position="none") + geom_point(data=temp, aes(CD79b.mean, light.mean), size=1) +
    geom_errorbar(data=temp, aes(x=CD79b.mean, y=NULL, ymin=light.mean-light.sem, ymax=light.mean+light.sem), width=0.03) +
    geom_errorbarh(data=temp, aes(x=NULL, y=light.mean, xmin=CD79b.mean-CD79b.sem, xmax=CD79b.mean+CD79b.sem), height=0.03)
  ggsave(paste0(ip, "figure_4h.eps"), height=2.5, width=11)
}


relativeImportance <- function(dt=dat, ip=images.path) {
  # Generates bar plots of contribution of variance explained
  # Inputs:
  #   dt - data.table
  #   ip - path to images folder
  # Outputs:
  #   eps image
  cd79b.imp <- calc.relimp(formula=CD79b~meta+isotype, data=dt, rela=T, type="lmg", rank=F)
  light.imp <- calc.relimp(formula=light~meta+isotype, data=dt, rela=T, type="lmg", rank=F)

  temp <- data.table(CD79b=cd79b.imp@lmg, light=light.imp@lmg, classification=c("phenotype", "isotype")) %>%
    melt(id.vars="classification", variable.name="marker", value.name="percent") %>%
    .[, percent:=percent*100] %>%
    .[, marker:=factor(marker, levels=c("CD79b", "light"))]

  ggplot(temp, aes(marker, percent, fill=classification)) + geom_bar(stat="identity") +
    theme_bw() + theme(legend.position="none", panel.grid=element_blank()) +
    scale_fill_manual(values=c("#a01ea0", "#25a3a3"))
  ggsave(paste0(ip, "figure_4i.eps"), width=1.5, height=4)
}



##### MAIN #####

if (!dir.exists(images.path)) dir.create(images.path)
dat <- fread(paste0(path, "processed_surface.csv"), stringsAsFactors=T) %>%
  .[, isotype:=factor(isotype, isotypes)] %>%
  .[, meta:=factor(meta, clusters)] %>%
  .[, cluster:=factor(cluster)] %>%
  .[, subject:=factor(subject)]

all.markers <- setdiff(colnames(dat), factors)
markers <- setdiff(all.markers, c("IgM", "IgD", "IgA", "IgG"))

medians <- dat[, lapply(.SD, median), .SDcols=all.markers, by=.(meta)] %>%
  .[order(meta)]

# Figure 4B
metaHeatmap()

# Figure 4D
makeUmap()

# Figure 4E
distanceHeatmap()

# Figure 4F
isotypeBar()

# Figure 4G
populationBar()

# Figure 4H
isotypeContours()

# Figure 4I
relativeImportance()
